In [ ]:
# Artificial Neural Network

# Installing Theano
# pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
# pip install tensorflow

# Installing Keras
# pip install --upgrade keras

# Part 1 - Data Preprocessing

In [ ]:
!pip install -r requirements.txt

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [3]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

In [4]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [5]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [6]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [7]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [8]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.4911 - acc: 0.7970
Epoch 2/100
8000/8000 [==============================] - 1s 90us/step - loss: 0.4206 - acc: 0.8234
Epoch 3/100
8000/8000 [==============================] - 1s 98us/step - loss: 0.4146 - acc: 0.8281
Epoch 4/100
8000/8000 [==============================] - 1s 133us/step - loss: 0.4103 - acc: 0.8299
Epoch 5/100
8000/8000 [==============================] - 1s 91us/step - loss: 0.4073 - acc: 0.8312
Epoch 6/100
8000/8000 [==============================] - 1s 96us/step - loss: 0.4054 - acc: 0.8311
Epoch 7/100
8000/8000 [==============================] - 1s 125us/step - loss: 0.4042 - acc: 0.8334
Epoch 8/100
8000/8000 [==============================] - 1s 101us/step - loss: 0.4028 - acc: 0.8327
Epoch 9/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.4014 - acc: 0.8335
Epoch 10/100
8000/8000 [==============================] 

8000/8000 [==============================] - 1s 69us/step - loss: 0.3375 - acc: 0.8590
Epoch 80/100
8000/8000 [==============================] - 1s 73us/step - loss: 0.3373 - acc: 0.8630
Epoch 81/100
8000/8000 [==============================] - 1s 70us/step - loss: 0.3369 - acc: 0.8630
Epoch 82/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.3362 - acc: 0.8614
Epoch 83/100
8000/8000 [==============================] - 1s 72us/step - loss: 0.3361 - acc: 0.8621
Epoch 84/100
8000/8000 [==============================] - 1s 70us/step - loss: 0.3365 - acc: 0.8602
Epoch 85/100
8000/8000 [==============================] - 1s 71us/step - loss: 0.3365 - acc: 0.8599
Epoch 86/100
8000/8000 [==============================] - 1s 81us/step - loss: 0.3368 - acc: 0.8605
Epoch 87/100
8000/8000 [==============================] - 1s 77us/step - loss: 0.3365 - acc: 0.8629
Epoch 88/100
8000/8000 [==============================] - 1s 72us/step - loss: 0.3361 - acc: 0.8619
Epoch 89/100


In [9]:

# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [10]:
cm

array([[1519,   76],
       [ 209,  196]])

In [11]:
# New classifier changing activation functions
# Initialising the ANN
classifier2 = Sequential()

# Adding the input layer and the first hidden layer
classifier2.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

# Adding the second hidden layer
classifier2.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Adding the output layer
classifier2.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'relu'))

# Compiling the ANN
classifier2.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [12]:
# Fitting the ANN to the Training set
classifier2.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 185us/step - loss: 0.5080 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 104us/step - loss: 0.4797 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.4442 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.4337 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 95us/step - loss: 0.4325 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 94us/step - loss: 0.4301 - acc: 0.7959
Epoch 7/100
8000/8000 [==============================] - 1s 96us/step - loss: 0.4325 - acc: 0.7955
Epoch 8/100
8000/8000 [==============================] - 1s 104us/step - loss: 0.4290 - acc: 0.7964
Epoch 9/100
8000/8000 [==============================] - 1s 99us/step - loss: 0.4289 - acc: 0.7957
Epoch 10/100
8000/8000 [==============================] - 1s 116us/step - loss: 0.4287 - acc: 0.7936
Epo

8000/8000 [==============================] - 1s 86us/step - loss: 0.3501 - acc: 0.8580
Epoch 83/100
8000/8000 [==============================] - 1s 85us/step - loss: 0.3526 - acc: 0.8570
Epoch 84/100
8000/8000 [==============================] - 1s 89us/step - loss: 0.3499 - acc: 0.8571
Epoch 85/100
8000/8000 [==============================] - 1s 89us/step - loss: 0.3510 - acc: 0.8580
Epoch 86/100
8000/8000 [==============================] - 1s 86us/step - loss: 0.3488 - acc: 0.8586
Epoch 87/100
8000/8000 [==============================] - 1s 80us/step - loss: 0.3486 - acc: 0.8569
Epoch 88/100
8000/8000 [==============================] - 1s 80us/step - loss: 0.3567 - acc: 0.8576
Epoch 89/100
8000/8000 [==============================] - 1s 81us/step - loss: 0.3488 - acc: 0.8577
Epoch 90/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.3497 - acc: 0.8571
Epoch 91/100
8000/8000 [==============================] - 1s 116us/step - loss: 0.3533 - acc: 0.8576
Epoch 92/10

In [13]:

# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier2.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [14]:
cm

array([[1513,   82],
       [ 202,  203]])

In [15]:
# New classifier changing activation functions
# Initialising the ANN
classifier3 = Sequential()

# Adding the input layer and the first hidden layer
classifier3.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier3.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier3.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'relu'))

# Compiling the ANN
classifier3.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [16]:
# Fitting the ANN to the Training set
classifier3.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 126us/step - loss: 3.2881 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 96us/step - loss: 3.2881 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 87us/step - loss: 3.2881 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 106us/step - loss: 3.2881 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 88us/step - loss: 3.2881 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 89us/step - loss: 3.2881 - acc: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 122us/step - loss: 3.2881 - acc: 0.7960
Epoch 8/100
8000/8000 [==============================] - 1s 92us/step - loss: 3.2881 - acc: 0.7960
Epoch 9/100
8000/8000 [==============================] - 1s 106us/step - loss: 3.2881 - acc: 0.7960
Epoch 10/100
8000/8000 [==============================] - 1s 91us/step - loss: 3.2881 - acc: 0.7960
Epoch

8000/8000 [==============================] - 1s 84us/step - loss: 3.2881 - acc: 0.7960
Epoch 83/100
8000/8000 [==============================] - 1s 80us/step - loss: 3.2881 - acc: 0.7960
Epoch 84/100
8000/8000 [==============================] - 1s 80us/step - loss: 3.2881 - acc: 0.7960
Epoch 85/100
8000/8000 [==============================] - 1s 80us/step - loss: 3.2881 - acc: 0.7960
Epoch 86/100
8000/8000 [==============================] - 1s 81us/step - loss: 3.2881 - acc: 0.7960
Epoch 87/100
8000/8000 [==============================] - 1s 80us/step - loss: 3.2881 - acc: 0.7960
Epoch 88/100
8000/8000 [==============================] - 1s 84us/step - loss: 3.2881 - acc: 0.7960
Epoch 89/100
8000/8000 [==============================] - 1s 82us/step - loss: 3.2881 - acc: 0.7960
Epoch 90/100
8000/8000 [==============================] - 1s 82us/step - loss: 3.2881 - acc: 0.7960
Epoch 91/100
8000/8000 [==============================] - 1s 81us/step - loss: 3.2881 - acc: 0.7960
Epoch 92/100


In [17]:

# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier3.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [18]:
cm

array([[1595,    0],
       [ 405,    0]])